-- Register the Hub-hosted MacTech AI gateway in the canonical application
-- registry. Railway runs `prisma migrate deploy` before Next.js starts, so
-- this idempotent upsert makes authorization available without relying on a
-- production seed operation.
INSERT INTO "AppRegistry" (
  "id",
  "appKey",
  "name",
  "description",
  "baseUrl",
  "status",
  "category",
  "requiresOrgContext",
  "isInternalOnly",
  "slug",
  "publicUrl",
  "adminUrl",
  "criticality",
  "lifecycle",
  "visibility",
  "repoFullName",
  "repoDefaultBranch",
  "railwayProjectId",
  "railwayServiceId",
  "railwayEnvironmentId",
  "railwayEnvironmentName",
  "operationalNotes",
  "createdAt",
  "updatedAt"
)
VALUES (
  'app_mactech_ai',
  'mactech-ai',
  'MacTech AI',
  'Tenant-aware Suite intelligence gateway with NVIDIA NIM inference, approved retrieval, controlled tools, human approvals, and Hub audit.',
  'https://www.suite.mactechsolutionsllc.com/admin/ai',
  'active',
  'admin',
  true,
  false,
  'mactech-ai',
  'https://www.suite.mactechsolutionsllc.com/admin/ai',
  'https://www.suite.mactechsolutionsllc.com/admin/ai/admin',
  'high',
  'production',
  'customer',
  'MacTech-Solutions-LLC/mactech-suite-platform',
  'main',
  'f89efd3b-289a-49cc-93f8-b9af2a7846d6',
  '1bd0fda3-22d4-4f54-8644-1b66aba6f4a1',
  '3470ce48-8ac5-47fd-93a4-de87ffc01666',
  'production',
  'Hub remains the authority for identity, tenancy, permissions, entitlements, approvals, and audit. Domain applications remain authoritative for their records.',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT ("appKey") DO UPDATE SET
  "name" = EXCLUDED."name",
  "description" = EXCLUDED."description",
  "baseUrl" = EXCLUDED."baseUrl",
  "status" = EXCLUDED."status",
  "category" = EXCLUDED."category",
  "requiresOrgContext" = EXCLUDED."requiresOrgContext",
  "isInternalOnly" = EXCLUDED."isInternalOnly",
  "slug" = EXCLUDED."slug",
  "publicUrl" = EXCLUDED."publicUrl",
  "adminUrl" = EXCLUDED."adminUrl",
  "criticality" = EXCLUDED."criticality",
  "lifecycle" = EXCLUDED."lifecycle",
  "visibility" = EXCLUDED."visibility",
  "repoFullName" = EXCLUDED."repoFullName",
  "repoDefaultBranch" = EXCLUDED."repoDefaultBranch",
  "railwayProjectId" = EXCLUDED."railwayProjectId",
  "railwayServiceId" = EXCLUDED."railwayServiceId",
  "railwayEnvironmentId" = EXCLUDED."railwayEnvironmentId",
  "railwayEnvironmentName" = EXCLUDED."railwayEnvironmentName",
  "operationalNotes" = EXCLUDED."operationalNotes",
  "updatedAt" = CURRENT_TIMESTAMP;
